---
title: "human_compression_evaluation_analysis"
output: html_notebook
---

### load necessary packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
library(lme4)
library(lmerTest)
library(tidyboot)
```


### load in ratings data 
```{r}
d <- read_csv('../../results/human_compression_ratings_hashed.csv')
```

### number of times each worker rated an image
```{r}
d %>% 
  group_by(WorkerID) %>% 
  tally()
```

### bootstrap mean rating
```{r}
d.bootstrap <- d %>% 
  group_by(compressor, image) %>% 
  tidyboot_mean(column=rating) 
```

## plot mean rating by image x compressor, sorted by human vs. webp difference magnitude
```{r}
d.bootstrap %>%
  select(compressor, image, empirical_stat) %>%
  spread(compressor, empirical_stat) %>%
  mutate(diff = human - webp) %>%
  select(image,diff) %>%
  left_join(d.bootstrap, d.diff, by=c('image')) %>%
  ggplot(aes(x = empirical_stat, y =  fct_reorder(factor(image), diff), 
                         color = compressor)) +
  geom_point() +
  geom_errorbarh(aes(xmax = ci_upper, xmin = ci_lower), height = 0) +
  theme_few() +
  ylab('image') +
  xlab('rating') +
  scale_x_continuous('rating', seq(1,10,1),seq(1,10,1), limits=c(1,10)) +
  theme(aspect.ratio = 1/2)

ggsave('../../plots/mean_ratings.pdf')
```

## Show bootstrapped confidence intervals for mean ratings for human vs. webp, for each image
```{r}
d.bootstrap
```


## fit data with lmer 
```{r}
m <- lmer(rating ~ compressor + (1 + compressor | image) + (1 + compressor | WorkerID), data = d)
summary(m)
```

